# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Blog personal
author: JuandeLS3
description: > # this means to ignore newlines until "baseurl:"
 Blog de JuandeLS3 ~ Sevillano y Desarrollador de Aplicaciones Web
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://juandels3.github.io/"
permalink: :title/
full-url: "https://juandels3.github.io/" # the base hostname & protocol for your site


# CSS
sass:
  style: compressed

# Comments - Go to Disqus.com > sign up > get the short-name > insert it here
disqus-shortname: 

# Tracker (editar)
analytics: UA-119603257-1

# Form Settings
#
# Contact form can be enabled by getting an API key from https://getsimpleform.com/
simpleform-token: af76965ad6e2b0be1ffb2d61576f5f64

# Redirect users after submitting the form
redirect-to: https://juandels3.github.io/

# Site version
version: 1.1


# Post date background - This will change the background of the post date and tag ribbon according to the theme. If set to no default green background will be used. If yes then the theme color scheme is used.

change-date-bg: no


# Build settings
markdown: kramdown

include: [_pages] # Includes files inside _pages directory [Do not remove this]

author:
  name: JuandeLS3
  image: juandels3.jpg # The author image will be shown on the header. Place this image in /images/ folder.
  about: Nací en España y resido actualmente en Sevilla, Andalucía.
         Estudio Desarrollo de Aplicaciones Web en el IES Polígono Sur y me encanta el mundo del
         desarrollo en general y los videojuegos.
  twitter: JuandeLS3  # https://twitter.com/ is automatically added
  #facebook: webjeda # https://facebook.com/ is automatically added
  email: juandelsal3@gmail.com # mailto: is automatically added
  
gems: 
  - jekyll-seo-tag
  - jekyll-paginate