title: ThinDev # your site title
author: JuandeLS3
email: juandelsal3@gmail.com # email for form submission, you also have to change it in _js/scripts.js
description: > # this means to ignore newlines until "baseurl:"
  Mi blog personal donde encontrarás contenido relacionado
  con desarrollo y videojuegos, dos de mis temáticas y hobbies
  favoritos
encoding:  UTF8
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://juandels3.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: juandels3 # replace with your_twitter_username or comment to remove link from footer
github_username:  juandels3 # replace with your_github_username or comment to remove link from footer
instagram_username: juandels3 # replace with your_instagram_username or comment to remove link from footer
social:
  name: Juan
  links:
    - https://twitter.com/juandels3
    #- https://www.facebook.com/ben.balter
    - https://www.linkedin.com/in/juandels3
    #- https://plus.google.com/+BenBalter
    - https://github.com/juandels3
    #- https://keybase.io/benbalter

disqus:
  shortname: juandels3 # to enable comments replace with your_disqus_shortname

# Build settings
markdown: kramdown
highlighter: rouge # or pygments or null
theme: jekyll-sleek
exclude:
  - README.md
  - node_modules
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js

include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
